Attribute VB_Name = "Module1"
Public X1 As Single
Public Y1 As Single
Public X2 As Single
Public Y2 As Single
Public X3 As Single
Public Y3 As Single
Public X4 As Single
Public Y4 As Single
Public X5 As Single
Public Y5 As Single
Public X6 As Single
Public Y6 As Single
Public X7 As Single
Public Y7 As Single
Public X8 As Single
Public Y8 As Single
Public X9 As Single
Public Y9 As Single
Public X10 As Single
Public Y10 As Single
Public X11 As Single
Public Y11 As Single
Public X12 As Single
Public Y12 As Single
